"""
Table of contents generation and header processing.

This module handles TOC generation and header anchor creation.
"""

from __future__ import annotations

import logging
import re
from typing import List, Dict, Any, Tuple

logger = logging.getLogger(__name__)


def generate_table_of_contents(html_content: str) -> str:
    """Generate a table of contents from headers in the HTML content.
    
    Extracts all headers (colored span elements) and creates anchor links.
    Returns the TOC HTML to be prepended to the content.
    
    [TOC_FORMAT] Subheaders are indented and displayed in a smaller font.
    
    Args:
        html_content: The rendered HTML content with anchor IDs already added
        
    Returns:
        TOC HTML string with links to all headers
    """
    import re
    
    # Find all headers (colored span elements that look like section headers)
    # After _add_header_anchors, the pattern is: <p id="header-X-slug"><span style="...">Header Text</span> [^]</p>
    # Also support <p class="h2-header" or <p class="h3-header" for Chapter 2 Athasian Society
    # Also find <h2> and <h3> tags that may be generated by __section_header markers
    # The header text may include roman numerals (e.g., "I. Warrior Classes")
    
    # Pattern for colored span headers - capture p tag attributes and extract class if present
    # The pattern allows for class and id in any order
    span_header_pattern = r'<p([^>]+)>(?:.*?)<span[^>]*style="([^"]*)"[^>]*>([^<]+)</span>'
    # Use finditer to get positions
    span_matches = []
    for m in re.finditer(span_header_pattern, html_content):
        p_attrs = m.group(1)  # All attributes from the p tag
        span_style = m.group(2)
        header_text = m.group(3)
        
        # Extract id from p attributes
        id_match = re.search(r'id="([^"]+)"', p_attrs)
        if not id_match:
            continue  # Skip if no id
        header_id = id_match.group(1)
        
        # Extract class from p attributes if present
        class_match = re.search(r'class="([^"]+)"', p_attrs)
        p_class = class_match.group(1) if class_match else ""
        
        # Combine p class and span style so we can check both
        combined_attrs = f"{p_class} {span_style}"
        span_matches.append((m.start(), header_id, combined_attrs, header_text))
    
    # Pattern for <h2> and <h3> tags
    h_tag_pattern = r'<(h[23]) id="([^"]+)">([^<]+)'
    h_matches = [(m.start(), m.group(1), m.group(2), m.group(3)) 
                  for m in re.finditer(h_tag_pattern, html_content)]
    
    # Combine all matches with positions: (position, header_id, style_attr/level, header_text)
    all_matches = []
    
    for pos, header_id, style_attr, header_text in span_matches:
        all_matches.append((pos, header_id, style_attr, header_text))
    
    # Convert h-tag matches to the same format
    for pos, tag_name, header_id, header_text in h_matches:
        # Map tag name to a style attribute that will be recognized
        if tag_name == 'h2':
            style_attr = 'class="header-h2"'
        elif tag_name == 'h3':
            style_attr = 'class="header-h3"'
        else:
            style_attr = ''
        all_matches.append((pos, header_id, style_attr, header_text.strip()))
    
    if not all_matches:
        return ""
    
    # Sort by position in document to maintain correct order
    all_matches.sort(key=lambda x: x[0])
    
    # Extract just the data we need (drop position)
    matches = [(header_id, style_attr, header_text) for pos, header_id, style_attr, header_text in all_matches]
    
    # Filter and categorize headers
    # Exclude very short headers that are likely table column headers
    # (e.g., "Age", "Base", "Race" when standalone without context)
    table_column_keywords = [
        'height in inches', 'weight in pounds', 'modifier', 'base', 'race',
        'base age', 'maximum age range', 'variable', 'r a c e',
        '(base + variable)', 'middle age*', 'old age**', 'venerable***'
    ]
    
    # Build TOC HTML with hierarchy
    toc_items = []
    for header_id, style_attr, header_text in matches:
        # Strip roman numerals from header text for TOC display (they were added by _add_header_anchors)
        # Roman numerals are like "I. ", "II. ", "III. ", etc.
        toc_display_text = re.sub(r'^[IVXLCDM]+\.\s+', '', header_text)
        
        header_lower = toc_display_text.lower().strip()
        
        # Skip table column headers
        if header_lower in table_column_keywords:
            continue
        
        # Check header level based on CSS class (or font-size for backward compatibility)
        # [HEADER_SIZE] H1 = default, H2 = 0.9em, H3 = 0.8em, H4 = 0.7em
        # Also check for h2-header and h3-header classes (Chapter 2 Athasian Society style)
        header_level = 'h1'  # default
        if ('class="header-h2"' in style_attr or "class='header-h2'" in style_attr or
            'h2-header' in style_attr):
            header_level = 'h2'
        elif ('class="header-h3"' in style_attr or "class='header-h3'" in style_attr or
              'h3-header' in style_attr):
            header_level = 'h3'
        elif 'class="header-h4"' in style_attr or "class='header-h4'" in style_attr:
            header_level = 'h4'
        elif 'class="header-h1"' in style_attr or "class='header-h1'" in style_attr:
            header_level = 'h1'
        else:
            # Backward compatibility: check font-size
            if 'font-size: 0.9em' in style_attr:
                header_level = 'h2'
            elif 'font-size: 0.8em' in style_attr:
                header_level = 'h3'
            elif 'font-size: 0.7em' in style_attr:
                header_level = 'h4'
        
        # [TOC_FORMAT] Apply appropriate class based on header level
        if header_level == 'h4':
            # H4 headers: most indented, smallest font
            toc_items.append(f'<li class="toc-subsubsubheader"><a href="#{header_id}">{toc_display_text}</a></li>')
        elif header_level == 'h3':
            # H3 headers: more indented, smaller font
            toc_items.append(f'<li class="toc-subsubheader"><a href="#{header_id}">{toc_display_text}</a></li>')
        elif header_level == 'h2':
            # H2 headers: indented, smaller font
            toc_items.append(f'<li class="toc-subheader"><a href="#{header_id}">{toc_display_text}</a></li>')
        else:
            # H1 headers: main headers with roman numerals
            toc_items.append(f'<li><a href="#{header_id}">{header_text}</a></li>')
    
    toc_html = f'''<nav id="table-of-contents">
<h2>Table of Contents</h2>
<ul>
{''.join(toc_items)}
</ul>
</nav>
'''
    
    return toc_html




def fix_chapter_6_armor_headers_after_anchoring(html_content: str) -> str:
    """Fix armor section headers in Chapter 6 after anchoring has been applied.
    
    - Add font-size: 0.9em to "Hide Armor:" header
    - Merge fragmented "Studded Leather..." headers (20, 21, 22)
    - Merge fragmented "Chain, Splint..." headers (23, 24)
    - Extract "Shields:" from paragraph text
    """
    import re
    
    # 1. Add font-size to "Hide Armor:" header (header-19)
    hide_pattern = r'(<p id="header-19-hide-armor">)([IVX]+\.\s+<a [^>]+>\[\^\]</a>\s+)(<span style="color: #ca5804">)(Hide Armor:</span></p>)'
    hide_replacement = r'\1\2<span style="color: #ca5804; font-size: 0.9em">\4'
    html_content = re.sub(hide_pattern, hide_replacement, html_content, flags=re.IGNORECASE)
    
    # 2. Merge fragmented "Studded Leather..." headers (20, 21, 22)
    # Pattern: header-20 + header-21 + header-22 + paragraph with "Armor:" + paragraph with content
    studded_pattern = (
        r'<p id="header-20-studded-leather-ring-mail-brigandine-and">[IVX]+\.\s+<a [^>]+>\[\^\]</a>\s+<span[^>]*>Studded Leather, Ring Mail, Brigandine, and</span></p>\s*'
        r'<p id="header-21-scale">[IVX]+\.\s+<a [^>]+>\[\^\]</a>\s+<span[^>]*>Scale\s*</span></p>\s*'
        r'<p id="header-22-mail">[IVX]+\.\s+<a [^>]+>\[\^\]</a>\s+<span[^>]*>Mail\s*</span></p>\s*'
        r'<p><span style="color: #ca5804">Armor:</span>\s*([^<]+)</p>'
    )
    studded_replacement = (
        r'<p id="header-20-studded-leather-ring-mail-brigandine-and-scale-mail-armor">XXI.  '
        r'<a href="#top" style="font-size: 0.8em; text-decoration: none;">[^]</a> '
        r'<span style="color: #ca5804; font-size: 0.9em">Studded Leather, Ring Mail, Brigandine, and Scale Mail Armor:</span></p>'
        r'\n<p>\1</p>'
    )
    html_content = re.sub(studded_pattern, studded_replacement, html_content, flags=re.IGNORECASE | re.DOTALL)
    
    # 3. Merge fragmented "Chain, Splint..." headers (23, 24)
    chain_pattern = (
        r'<p id="header-23-chain-splint-banded-bronze-plate-or-plate">[IVX]+\.\s+<a [^>]+>\[\^\]</a>\s+<span[^>]*>Chain, Splint, Banded, Bronze Plate, or Plate\s*</span></p>\s*'
        r'<p id="header-24-mail;-field-plate-and-full-plate-armor">[IVX]+\.\s+<a [^>]+>\[\^\]</a>\s+<span[^>]*>Mail; Field Plate and Full Plate Armor:</span></p>'
    )
    chain_replacement = (
        r'<p id="header-23-chain-splint-banded-bronze-plate-or-plate-mail-field-plate-and-full-plate-armor">XXIV.  '
        r'<a href="#top" style="font-size: 0.8em; text-decoration: none;">[^]</a> '
        r'<span style="color: #ca5804; font-size: 0.9em">Chain, Splint, Banded, Bronze Plate, or Plate Mail; Field Plate and Full Plate Armor:</span></p>'
    )
    html_content = re.sub(chain_pattern, chain_replacement, html_content, flags=re.IGNORECASE | re.DOTALL)
    
    # 4. Extract "Shields:" from paragraph and create a header with Roman numeral XVII
    shields_pattern = r'(<p>Many types of armor can be constructed without metal on Athas, using more readily available materials\.\s+)(Shields:)(Shields are [^<]+</p>)'
    shields_replacement = (
        r'\1</p>\n'
        r'<p id="header-shields">XVII.  <a href="#top" style="font-size: 0.8em; text-decoration: none;">[^]</a> '
        r'<span style="color: #ca5804; font-size: 0.9em">\2</span></p>\n'
        r'<p>\3'
    )
    html_content = re.sub(shields_pattern, shields_replacement, html_content, flags=re.IGNORECASE | re.DOTALL)
    
    # 5. Apply H2 styling to existing armor headers that already have Roman numerals
    existing_armor_headers = [
        "Alternate Materials:",
        "Leather Armor:",
        "Padded Armor:",
    ]
    
    for header in existing_armor_headers:
        # Find header with Roman numeral and add font-size styling to the span
        # Pattern: <p id="...">ROMAN.  <a...>[^]</a> <span style="color: #ca5804">HEADER</span></p>
        pattern = rf'(<p id="[^"]+">)([IVX]+\.\s+<a [^>]+>\[\^\]</a>\s+)(<span style="color: #ca5804">)({re.escape(header)}</span></p>)'
        replacement = rf'\1\2<span style="color: #ca5804; font-size: 0.9em">\4'
        html_content = re.sub(pattern, replacement, html_content, flags=re.IGNORECASE)
    
    return html_content




def apply_subheader_styling(html_content: str, slug: str | None = None) -> str:
    """Apply CSS classes and font-size styling to headers that should be subheaders.
    
    This must be done BEFORE TOC generation so the TOC can detect subheaders.
    Now uses semantic CSS classes (header-h2, header-h3, header-h4) for proper
    header level detection, with inline font-size retained for visual compatibility.
    
    Refactored to follow best practices - broken into focused helper functions.
    
    Args:
        html_content: The rendered HTML content
        slug: Section slug for chapter-specific styling
        
    Returns:
        HTML content with subheader styling and CSS classes applied
    """
    # Get chapter-specific patterns
    subheader_patterns = _get_subheader_patterns(slug)
    
    # Apply all patterns
    html_content = _apply_patterns(html_content, subheader_patterns)
    
    # Add CSS classes based on font-size
    html_content = _add_header_css_classes(html_content)
    
    return html_content


def _get_subheader_patterns(slug: str | None) -> List[Tuple[str, str]]:
    """Get subheader patterns for a specific chapter.
    
    Args:
        slug: Section slug
        
    Returns:
        List of (pattern, replacement) tuples
    """
    if slug == "chapter-one-ability-scores":
        return _get_chapter_one_ability_patterns()
    elif slug == "chapter-one-the-world-of-athas":
        return _get_chapter_one_world_patterns()
    elif slug == "chapter-two-player-character-races":
        return _get_chapter_two_race_patterns()
    elif slug == "chapter-three-player-character-classes":
        return _get_chapter_three_class_patterns()
    elif slug == "chapter-fourteen-time-and-movement":
        return _get_chapter_fourteen_time_patterns()
    elif slug == "chapter-six-money-and-equipment":
        return _get_chapter_six_equipment_patterns()
    elif slug == "chapter-seven-magic":
        return _get_chapter_seven_magic_patterns()
    elif slug == "chapter-eight-experience":
        return _get_chapter_eight_experience_patterns()
    elif slug == "chapter-nine-combat":
        return _get_chapter_nine_combat_patterns()
    elif slug == "chapter-ten-treasure":
        return _get_chapter_ten_treasure_patterns()
    elif slug == "chapter-fifteen-new-spells":
        return _get_chapter_fifteen_spells_patterns()
    return []


def _get_chapter_one_ability_patterns() -> List[Tuple[str, str]]:
    """Get subheader patterns for Chapter One: Ability Scores."""
    return [
        (r'<span style="color: #ca5804">(Optional Method I: </span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Optional Method II: </span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Optional Method III: </span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Optional Method IV: </span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Optional Method V: </span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Intelligence: </span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Wisdom: </span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
    ]


def _get_chapter_one_world_patterns() -> List[Tuple[str, str]]:
    """Get subheader patterns for Chapter One: The World of Athas."""
    return [
        (r'<span style="color: #(?:ca5804|cd490a)">(Clerical Magic</span>)', r'<span style="color: #cd490a; font-size: 0.9em">\1'),
        (r'<span style="color: #(?:ca5804|cd490a)">(Wizardry</span>)', r'<span style="color: #cd490a; font-size: 0.9em">\1'),
        (r'<span style="color: #(?:ca5804|cd490a)">(Psionics</span>)', r'<span style="color: #cd490a; font-size: 0.9em">\1'),
    ]


def _get_chapter_two_race_patterns() -> List[Tuple[str, str]]:
    """Get subheader patterns for Chapter Two: Player Character Races."""
    return [
        (r'<span style="color: #ca5804">(Racial Ability Requirements</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Table 2: Ability Adjustments</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Table 3: Racial Class And Level Limits</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Starting Age</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Aging Effects</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Roleplaying: </span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
    ]


def _get_chapter_three_class_patterns() -> List[Tuple[str, str]]:
    """Get subheader patterns for Chapter Three: Player Character Classes."""
    base_patterns = [
        (r'<span style="color: #ca5804">(Class Ability Requirements</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Fighters Followers</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Rangers Followers</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Defiler Experience Levels</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Templar Spell Progression</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Bard Poison Table</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Thieving Skill Exceptional Dexterity Adjustments</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Thieving Skill Racial Adjustments</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Inherent Potential Table</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Multi-Class Combinations</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
    ]
    
    # Multi-class race headers
    race_patterns = [
        (r'<span style="color: #ca5804">(Dwarf</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Elf or Half-elf</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(XXXIII\. )?Half-giant</span>', r'<span style="color: #ca5804; font-size: 0.9em">Half-giant</span>'),
        (r'<span style="color: #ca5804">(Halfling</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Mul</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Thri-kreen</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
    ]
    
    # Additional sections
    additional_patterns = [
        (r'<span style="color: #ca5804">(Dual-Class Characters</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Setting Up a Character Tree</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Changing Characters</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Between Adventures</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(During an Adventure</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Upon an Active Characters Death</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Character Advancement</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(The Status of Inactive Characters</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Using the Character Tree to Advantage</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Exchanges Between Characters</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Cleric Weapons Restrictions</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Possible Guardian Lands</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Spheres of Magic</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Roleplaying</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Roleplaying: </span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
    ]
    
    # Elemental planes (H3)
    elemental_patterns = [
        (r'<span style="color: #ca5804">Elemental Plane of Earth[^<]*</span>', r'<span style="color: #ca5804; font-size: 0.8em">Elemental Plane of Earth </span>'),
        (r'<span style="color: #ca5804">Elemental Plane of Air[^<]*</span>', r'<span style="color: #ca5804; font-size: 0.8em">Elemental Plane of Air </span>'),
        (r'<span style="color: #ca5804">Elemental Plane of Fire[^<]*</span>', r'<span style="color: #ca5804; font-size: 0.8em">Elemental Plane of Fire </span>'),
        (r'<span style="color: #ca5804">Elemental Plane of Water[^<]*</span>', r'<span style="color: #ca5804; font-size: 0.8em">Elemental Plane of Water </span>'),
    ]
    
    # Table column headers
    table_headers = [
        (r'<span style="color: #ca5804">(Die</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Onset</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Class</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Method</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Strength</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Roll</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Level</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Spell Level</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(L e v e l</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Pick.*Open.*Find.*Move.*Hide in</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Dex</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Pockets Locks Remove Silently Shadows</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(S k i l l</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Psionicist</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(E l f</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
    ]
    
    return base_patterns + race_patterns + additional_patterns + elemental_patterns + table_headers


def _apply_patterns(html_content: str, patterns: List[Tuple[str, str]]) -> str:
    """Apply regex patterns to HTML content.
    
    Args:
        html_content: HTML to process
        patterns: List of (pattern, replacement) tuples
        
    Returns:
        Processed HTML
    """
    import re
    for pattern, replacement in patterns:
        html_content = re.sub(pattern, replacement, html_content)
    return html_content


def _add_header_css_classes(html_content: str) -> str:
    """Add CSS classes based on font-size values.
    
    Args:
        html_content: HTML to process
        
    Returns:
        HTML with CSS classes added
    """
    import re
    
    # H2 headers: font-size: 0.9em
    html_content = re.sub(
        r'<span style="color: #ca5804; font-size: 0\.9em"',
        r'<span class="header-h2" style="color: #ca5804; font-size: 0.9em"',
        html_content
    )
    # H3 headers: font-size: 0.8em
    html_content = re.sub(
        r'<span style="color: #ca5804; font-size: 0\.8em"',
        r'<span class="header-h3" style="color: #ca5804; font-size: 0.8em"',
        html_content
    )
    # H4 headers: font-size: 0.7em
    html_content = re.sub(
        r'<span style="color: #ca5804; font-size: 0\.7em"',
        r'<span class="header-h4" style="color: #ca5804; font-size: 0.7em"',
        html_content
    )
    
    return html_content


def _get_chapter_fourteen_time_patterns() -> List[Tuple[str, str]]:
    """Get subheader patterns for Chapter Fourteen: Time and Movement."""
    h2_patterns = [
        (r'<span style="color: #ca5804">(Year of the Messenger</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Starting the Campaign</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Water Consumption</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Substituting Other Liquids</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Effects of Dehydration</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Rehydration</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Animals and Dehydration</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Terrain Modifiers in Overland Movement</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Mounted Overland Movement</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Use of Vehicles</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
    ]
    h3_patterns = [
        (r'<span style="color: #ca5804">(Unusual Races</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Dehydration Effects Table</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Example of Dehydration</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Transporting Water</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Terrain Costs F o r Overland Movement</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Half-giants and Thri-kreen</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Care of Animals</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
    ]
    h4_patterns = [
        (r'<span style="color: #ca5804">(Thri-kreen:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
        (r'<span style="color: #ca5804">(Half-giants:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
        (r'<span style="color: #ca5804">(Kank:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
        (r'<span style="color: #ca5804">(Inix:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
        (r'<span style="color: #ca5804">(Mekillot:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
    ]
    return h2_patterns + h3_patterns + h4_patterns


def _get_chapter_six_equipment_patterns() -> List[Tuple[str, str]]:
    """Get subheader patterns for Chapter Six: Money and Equipment."""
    h2_patterns = [
        # Monetary Systems
        (r'<span style="color: #ca5804">(Barter:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Simple Barter:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Protracted Barter:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Service:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Initial Character Funds</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Metal Armor in Dark Sun:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        # Armor section
        (r'<span style="color: #ca5804">(Alternate Materials:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Shields:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Leather Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Padded Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Hide Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Studded Leather, Ring Mail, Brigandine, and Scale Mail Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Chain, Splint, Banded, Bronze Plate, or Plate Mail; Field Plate and Full Plate Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        # Fragmented armor headers
        (r'<span style="color: #ca5804">(Studded Leather, Ring Mail, Brigandine, and</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Scale</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Mail</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Chain, Splint, Banded, Bronze Plate, or Plate</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Mail; Field Plate and Full Plate Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        # New Equipment section
        (r'<span style="color: #ca5804">(Household Provisions</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Tack and Harness</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Transport</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Animals</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Transportation</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
    ]
    h3_patterns = [
        (r'<span style="color: #ca5804">(Common Wages</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Barding</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Barding:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Weapon Materials Table</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Tun of Water:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Fire Kit:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Chariot:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Howdah:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Wagons, open:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Wagons, enclosed:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Wagon, armored caravan:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Erdlu:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Inix:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Kank:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Mekillot:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Chatkcha:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Gythka:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Impaler:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Quabone:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Wrist Razor:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
    ]
    return h2_patterns + h3_patterns


def _get_chapter_seven_magic_patterns() -> List[Tuple[str, str]]:
    """Get subheader patterns for Chapter Seven: Magic."""
    return [
        # Sphere headers (H3)
        (r'<span style="color: #ca5804">(Sphere of Earth</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Sphere of Air</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Sphere of Fire</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Sphere of Water</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Sphere of the Cosmos</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        # Defiling section
        (r'<span style="color: #ca5804">(Defiling</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Casting Defiler Spells:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Defiler Magical Destruction Table</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
    ]


def _get_chapter_eight_experience_patterns() -> List[Tuple[str, str]]:
    """Get subheader patterns for Chapter Eight: Experience."""
    return [
        (r'<span style="color: #ca5804">(Fighter:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Gladiator :</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Ranger:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Preserver:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Defiler:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Cleric:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Druid:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Templar:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Rogues:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Thief:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Bard:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
    ]


def _get_chapter_nine_combat_patterns() -> List[Tuple[str, str]]:
    """Get subheader patterns for Chapter Nine: Combat."""
    h3_patterns = [
        # Game types
        (r'<span style="color: #ca5804">(Games:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Matinee:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Grudge Match:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Trial by Combat:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Matched Pairs:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Bestial Combat:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Test of Champions:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Advanced Games:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        # Piecemeal Armor
        (r'<span style="color: #ca5804">(Bonus to AC Per Type of Piece</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
    ]
    h2_patterns = [
        (r'<span style="color: #ca5804">(Stables:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Wagering:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Trading of Gladiators:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Turning Undead:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Commanding Undead:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Hovering on Death.+?s Door \(Optional Rule\)</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Followers</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Important Considerations</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
    ]
    return h3_patterns + h2_patterns


def _get_chapter_ten_treasure_patterns() -> List[Tuple[str, str]]:
    """Get subheader patterns for Chapter Ten: Treasure."""
    return [
        # H2 headers
        (r'<span style="color: #ca5804">(Lair Treasures</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Individual and Small Lair Treasures</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Coins</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Gems</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Objects of Art</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        # H3 headers
        (r'<span style="color: #ca5804">(Gem Table</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
    ]


def _get_chapter_fifteen_spells_patterns() -> List[Tuple[str, str]]:
    """Get subheader patterns for Chapter Fifteen: New Spells."""
    spell_levels = [
        (r'<span style="color: #ca5804">(First Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Second[\s\-]?Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Third Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Fourth Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Fifth[\s\-]?Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Sixth Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Seventh[\s\-]?Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        (r'<span style="color: #ca5804">(Eighth Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
    ]
    spell_names = [
        (r'<span style="color: #ca5804">(Charm Person</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Find Familiar</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        (r'<span style="color: #ca5804">(Mount</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
    ]
    return spell_levels + spell_names
    """
    
    Modifies colored span headers to include IDs for TOC linking.
    Also adds roman numerals to main headers and back-to-top links.
    
    Args:
        html_content: The rendered HTML content
        
    Returns:
        HTML content with header anchor IDs, roman numerals, and back-to-top links added
    """
    import re
    
    def int_to_roman(num: int) -> str:
        """Convert an integer to roman numerals."""
        values = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1]
        numerals = ['M', 'CM', 'D', 'CD', 'C', 'XC', 'L', 'XL', 'X', 'IX', 'V', 'IV', 'I']
        result = ''
        for i, val in enumerate(values):
            count = num // val
            if count:
                result += numerals[i] * count
                num -= val * count
        return result
    
    # Find all headers and add IDs
    # Pattern must capture full style attribute including optional "; font-size: 0.9em"
    # Allow for attributes on the <p> tag (e.g., data-force-break="true")
    header_pattern = r'<p(?:[^>]*)><span([^>]*)>([^<]+)</span></p>'
    
    def should_process_header(span_attrs: str) -> bool:
        """Check if this span is a header (has the header color or header CSS class)."""
        return ('style="color: #ca5804' in span_attrs or "style='color: #ca5804" in span_attrs 
                or 'style="color: #cd490a' in span_attrs or "style='color: #cd490a" in span_attrs
                or 'class="header-h' in span_attrs or "class='header-h" in span_attrs)
    
    def get_header_level(span_attrs: str) -> str:
        """Get the semantic header level from CSS class.
        
        [HEADER_NUMERALS] Only H1 headers get Roman numerals, not H2/H3/H4.
        
        Returns:
            'h1' for main headers, 'h2' for subheaders, 'h3' for sub-subheaders, 'h4' for smallest
        """
        if 'class="header-h2"' in span_attrs or "class='header-h2'" in span_attrs:
            return 'h2'
        elif 'class="header-h3"' in span_attrs or "class='header-h3'" in span_attrs:
            return 'h3'
        elif 'class="header-h4"' in span_attrs or "class='header-h4'" in span_attrs:
            return 'h4'
        elif 'class="header-h1"' in span_attrs or "class='header-h1'" in span_attrs:
            return 'h1'
        else:
            # Backward compatibility: check for font-size-based styling
            # This allows gradual migration to CSS classes
            if 'font-size: 0.9em' in span_attrs:
                return 'h2'
            elif 'font-size: 0.8em' in span_attrs:
                return 'h3'
            elif 'font-size: 0.7em' in span_attrs:
                return 'h4'
            # Default to H1 if no class or font-size indicator
            return 'h1'
    
    def should_add_roman_numeral(span_attrs: str) -> bool:
        """Check if this header should get a roman numeral.
        
        [HEADER_NUMERALS] Only H1 headers (main sections) get roman numerals, not H2/H3/H4.
        """
        return get_header_level(span_attrs) == 'h1'
    
    def replace_header(match):
        span_attrs = match.group(1)
        header_text = match.group(2)
        
        # Only process if this is actually a header (has the header color)
        if not should_process_header(span_attrs):
            return match.group(0)  # Return unchanged
        
        # Create a slug-friendly ID
        counter = replace_header.counter
        replace_header.counter += 1
        header_id = f"header-{counter}-{header_text.lower().replace(' ', '-').replace(':', '').replace('(', '').replace(')', '').replace(',', '')}"
        
        # [HEADER_NUMERALS] Add roman numerals to main headers (H1 only, not H2/H3/H4)
        # Check semantic header level via CSS class or font-size (backward compat)
        display_text = header_text
        if should_add_roman_numeral(span_attrs):
            # This is an H1 header - add roman numeral
            roman_counter = replace_header.roman_counter
            replace_header.roman_counter += 1
            roman_numeral = int_to_roman(roman_counter)
            # Place roman numeral outside the colored span so tests can match the raw header text
            # Visual result: "X. " before the colored header span
            prefix = f"{roman_numeral}. "
        else:
            prefix = ""
        
        # [HEADER_FORMAT] Add back-to-top link after every header
        back_to_top = ' <a href="#top" style="font-size: 0.8em; text-decoration: none;">[^]</a>'
        
        # Add appropriate class attribute for semantic header conversion
        header_level = get_header_level(span_attrs)
        class_attr = f' class="{header_level}-header"'
        
        return f'<p id="{header_id}"{class_attr}>{prefix}{back_to_top} <span{span_attrs}>{display_text}</span></p>'
    
    replace_header.counter = 0
    replace_header.roman_counter = 1
    
    # Add an anchor at the top of the document for back-to-top links
    if '<body>' in html_content:
        html_content = html_content.replace('<body>', '<body><a id="top"></a>')
    else:
        # If no <body> tag, add it at the beginning
        html_content = '<a id="top"></a>' + html_content
    
    return re.sub(header_pattern, replace_header, html_content)


def apply_subheader_styling(html_content: str, slug: str | None = None) -> str:
    """Apply sub-header styling to specific headers in the HTML content.
    
    [HEADER_NUMERALS] Only H1 headers get Roman numerals. H2/H3/H4 do NOT.
    This function marks headers as H2/H3/H4 by adding font-size styling.
    Later, add_header_anchors() will see these and skip adding Roman numerals.
    
    Args:
        html_content: The rendered HTML content
        slug: Optional slug to apply slug-specific patterns
        
    Returns:
        HTML content with subheader styling applied
    """
    import re
    
    # Determine which patterns to apply based on slug
    subheader_patterns = []
    
    if slug == "chapter-one-the-world-of-athas":
        subheader_patterns = [
            (r'<span style="color: #ca5804">(Racial Ability Requirements</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Table 2: Ability Adjustments</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Table 3: Racial Class And Level Limits</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Starting Age</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Aging Effects</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Roleplaying: </span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        ]
    elif slug == "chapter-three-player-character-classes":
        # Chapter 3 headers with hierarchy:
        # - H1 (default): Warriors, Wizard, Priest, Rogue
        # - H2 (0.9em): Starting Level, Starting Proficiencies, Starting Money, Class Ability Requirements, Multi-Class Combinations, race headers
        # - H3 (0.8em): Fighter, Gladiator, Ranger, Defiler, Preserver, Illusionist, Cleric, Druid, Templar, Bard, Thief
        # - H4 (0.7em): Fighters Followers, Rangers Followers, Defiler Experience Levels, Sphere headers, etc.
        subheader_patterns = [
            # H2: Main document sections
            (r'<span style="color: #ca5804">(Starting Level</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Starting Proficiencies</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Starting Money</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Class Ability Requirements</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Multi-Class Combinations</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H2: Multi-class race headers (should be subheaders within Multi-Class section)
            (r'<span style="color: #ca5804">(Dwarf</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Elf or Half-elf</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H3: Class names
            (r'<span style="color: #ca5804">(Fighter</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Gladiator</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Ranger</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Defiler</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Preserver</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Illusionist</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Cleric</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Druid</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Templar</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Bard</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Thief</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            # H4: Subsections
            (r'<span style="color: #ca5804">(Fighters Followers</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(Rangers Followers</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(Defiler Experience Levels</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(Sphere of Earth:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(Sphere of Air:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(Sphere of Fire:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(Sphere of Water:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(Templar Spell Progression</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(XXXIII\. )?Half-giant</span>', r'<span style="color: #ca5804; font-size: 0.9em">Half-giant</span>'),  # Remove Roman numeral if present, add subheader styling
            (r'<span style="color: #ca5804">(Halfling</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Mul</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Thri-kreen</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Dual-Class Characters</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Setting Up a Character Tree</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Changing Characters</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Between Adventures</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(During an Adventure</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Upon an Active Characters Death</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Character Advancement</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(The Status of Inactive Characters</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Using the Character Tree to Advantage</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Exchanges Between Characters</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Cleric Weapons Restrictions</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Possible Guardian Lands</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Spheres of Magic</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Roleplaying</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Roleplaying: </span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # Elemental Plane headers (H3) - NO Roman numerals, smaller than H2
            # [HEADER_SIZE] H3 headers use font-size: 0.8em to be visually distinct from H2 (0.9em)
            (r'<span style="color: #ca5804">Elemental Plane of Earth[^<]*</span>', r'<span style="color: #ca5804; font-size: 0.8em">Elemental Plane of Earth </span>'),
            (r'<span style="color: #ca5804">Elemental Plane of Air[^<]*</span>', r'<span style="color: #ca5804; font-size: 0.8em">Elemental Plane of Air </span>'),
            (r'<span style="color: #ca5804">Elemental Plane of Fire[^<]*</span>', r'<span style="color: #ca5804; font-size: 0.8em">Elemental Plane of Fire </span>'),
            (r'<span style="color: #ca5804">Elemental Plane of Water[^<]*</span>', r'<span style="color: #ca5804; font-size: 0.8em">Elemental Plane of Water </span>'),
            # Table column headers - these should definitely be subheaders
            (r'<span style="color: #ca5804">(Die</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Onset</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Class</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Method</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Strength</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Roll</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Level</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Spell Level</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # Note: "Templar" class header should be H1, not subheader - removed from this list
            (r'<span style="color: #ca5804">(L e v e l</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Pick.*Open.*Find.*Move.*Hide in</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Dex</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Pockets Locks Remove Silently Shadows</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(S k i l l</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Dwarf</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Psionicist</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Halfling</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(E l f</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        ]
    elif slug == "chapter-fourteen-time-and-movement":
        # Chapter 14 header level patterns
        # H2: font-size: 0.9em
        # H3: font-size: 0.8em
        # H4: font-size: 0.7em
        subheader_patterns = [
            # H2 headers
            (r'<span style="color: #ca5804">(Year of the Messenger</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Starting the Campaign</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Water Consumption</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Substituting Other Liquids</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Effects of Dehydration</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Rehydration</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Animals and Dehydration</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Terrain Modifiers in Overland Movement</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Mounted Overland Movement</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Use of Vehicles</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H3 headers
            (r'<span style="color: #ca5804">(Unusual Races</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Dehydration Effects Table</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Example of Dehydration</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Transporting Water</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Terrain Costs F o r Overland Movement</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Half-giants and Thri-kreen</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Care of Animals</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            # H4 headers
            (r'<span style="color: #ca5804">(Thri-kreen:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(Half-giants:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(Kank:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(Inix:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
            (r'<span style="color: #ca5804">(Mekillot:</span>)', r'<span style="color: #ca5804; font-size: 0.7em">\1'),
        ]
    elif slug == "chapter-six-money-and-equipment":
        # Chapter 6 H2 and H3 headers should NOT get Roman numerals
        # [HEADER_NUMERALS] Only H1 headers get Roman numerals, not H2 (0.9em) or H3 (0.8em)
        subheader_patterns = [
            # H2 headers (font-size: 0.9em) - Monetary Systems section
            (r'<span style="color: #ca5804">(Barter:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Simple Barter:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Protracted Barter:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Service:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Initial Character Funds</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Metal Armor in Dark Sun:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H2 headers - Armor section
            (r'<span style="color: #ca5804">(Alternate Materials:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Shields:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Leather Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Padded Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Hide Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Studded Leather, Ring Mail, Brigandine, and Scale Mail Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Chain, Splint, Banded, Bronze Plate, or Plate Mail; Field Plate and Full Plate Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H2 headers - Fragmented armor headers (these should be merged but aren't)
            # Treat them as H2 so they don't get Roman numerals
            (r'<span style="color: #ca5804">(Studded Leather, Ring Mail, Brigandine, and</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Scale</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Mail</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Chain, Splint, Banded, Bronze Plate, or Plate</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Mail; Field Plate and Full Plate Armor:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H2 headers - New Equipment section
            (r'<span style="color: #ca5804">(Household Provisions</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Tack and Harness</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Transport</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Animals</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H2 headers - Equipment Descriptions section
            (r'<span style="color: #ca5804">(Transportation</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H3 headers (font-size: 0.8em)
            (r'<span style="color: #ca5804">(Common Wages</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Barding</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # First occurrence (H3 under Tack and Harness in New Equipment)
            (r'<span style="color: #ca5804">(Barding:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # Second occurrence (H3 in Equipment Descriptions > Tack and Harness)
            (r'<span style="color: #ca5804">(Weapon Materials Table</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Tun of Water:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Household Provisions
            (r'<span style="color: #ca5804">(Fire Kit:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Household Provisions
            (r'<span style="color: #ca5804">(Chariot:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Transportation
            (r'<span style="color: #ca5804">(Howdah:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Transportation
            (r'<span style="color: #ca5804">(Wagons, open:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Transportation
            (r'<span style="color: #ca5804">(Wagons, enclosed:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Transportation
            (r'<span style="color: #ca5804">(Wagon, armored caravan:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Transportation
            (r'<span style="color: #ca5804">(Erdlu:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Animals
            (r'<span style="color: #ca5804">(Inix:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Animals
            (r'<span style="color: #ca5804">(Kank:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Animals
            (r'<span style="color: #ca5804">(Mekillot:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Animals
            (r'<span style="color: #ca5804">(Chatkcha:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Weapons
            (r'<span style="color: #ca5804">(Gythka:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Weapons
            (r'<span style="color: #ca5804">(Impaler:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Weapons
            (r'<span style="color: #ca5804">(Quabone:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Weapons
            (r'<span style="color: #ca5804">(Wrist Razor:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3 under Equipment Descriptions > Weapons
        ]
    elif slug == "chapter-seven-magic":
        # Chapter 7 H3 headers (spheres) should NOT get Roman numerals
        # [HEADER_NUMERALS] Only H1 headers get Roman numerals, not H2/H3 (0.9em/0.8em)
        subheader_patterns = [
            # Sphere headers (H3) - subsections under "Priestly Magic" (H1)
            (r'<span style="color: #ca5804">(Sphere of Earth</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Sphere of Air</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Sphere of Fire</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Sphere of Water</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Sphere of the Cosmos</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            # Defiling section headers
            (r'<span style="color: #ca5804">(Defiling</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),  # H2
            (r'<span style="color: #ca5804">(Casting Defiler Spells:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3
            (r'<span style="color: #ca5804">(Defiler Magical Destruction Table</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),  # H3
        ]
    elif slug == "chapter-eight-experience":
        # Chapter 8 H2 headers for class descriptions section
        # [HEADER_NUMERALS] Only H1 headers get Roman numerals, not H2 (0.9em)
        # These are the class name headers in the second "Individual Class Awards" section
        subheader_patterns = [
            # Class name headers (H2) in the description section
            (r'<span style="color: #ca5804">(Fighter:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Gladiator :</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Ranger:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Preserver:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Defiler:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Cleric:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Druid:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Templar:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Rogues:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Thief:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Bard:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
        ]
    elif slug == "chapter-nine-combat":
        # Chapter 9 Arena Combats section headers
        # Game types should be H3 (0.8em), other sections should be H2 (0.9em)
        subheader_patterns = [
            # H3 game type headers under Arena Combats
            (r'<span style="color: #ca5804">(Games:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Matinee:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Grudge Match:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Trial by Combat:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Matched Pairs:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Bestial Combat:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Test of Champions:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Advanced Games:</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            # H2 section headers - Arena Combats
            (r'<span style="color: #ca5804">(Stables:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Wagering:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Trading of Gladiators:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H2 section headers - Turning and Controlling Undead
            (r'<span style="color: #ca5804">(Turning Undead:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Commanding Undead:</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H2 section header - Hovering on Death's Door (Optional Rule) - handle \x92 apostrophe
            (r'<span style="color: #ca5804">(Hovering on Death.+?s Door \(Optional Rule\)</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H2 section header - Followers (combat-related)
            (r'<span style="color: #ca5804">(Followers</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H2 section header - Important Considerations (Piecemeal Armor)
            (r'<span style="color: #ca5804">(Important Considerations</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H3 section header - Bonus to AC Per Type of Piece (Piecemeal Armor)
            (r'<span style="color: #ca5804">(Bonus to AC Per Type of Piece</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        ]
    elif slug == "chapter-ten-treasure":
        # Chapter 10 Treasure section headers
        # [HEADER_NUMERALS] Only H1 headers get Roman numerals, not H2/H3 (0.9em/0.8em)
        subheader_patterns = [
            # H2 section headers (0.9em)
            (r'<span style="color: #ca5804">(Lair Treasures</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Individual and Small Lair Treasures</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Coins</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Gems</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Objects of Art</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # H3 section headers (0.8em)
            (r'<span style="color: #ca5804">(Gem Table</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        ]
    elif slug == "chapter-fifteen-new-spells":
        # Chapter 15 spell level headers (H2) and individual spell names (H3)
        # [HEADER_NUMERALS] Only H1 headers get Roman numerals, not H2/H3
        subheader_patterns = [
            # Spell level groups should be H2 (0.9em)
            (r'<span style="color: #ca5804">(First Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Second[\s\-]?Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Third Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Fourth Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Fifth[\s\-]?Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Sixth Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Seventh[\s\-]?Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            (r'<span style="color: #ca5804">(Eighth Level Spells</span>)', r'<span style="color: #ca5804; font-size: 0.9em">\1'),
            # Individual spell names under First Level should be H3 (0.8em)
            (r'<span style="color: #ca5804">(Charm Person</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Find Familiar</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
            (r'<span style="color: #ca5804">(Mount</span>)', r'<span style="color: #ca5804; font-size: 0.8em">\1'),
        ]
    
    for pattern, replacement in subheader_patterns:
        html_content = re.sub(pattern, replacement, html_content)
    
    # Post-processing: Add CSS classes based on font-size values
    # This provides semantic header levels for proper logic while maintaining visual styling
    # H2 headers: font-size: 0.9em → add class="header-h2"
    html_content = re.sub(
        r'<span style="color: #ca5804; font-size: 0\.9em"',
        r'<span class="header-h2" style="color: #ca5804; font-size: 0.9em"',
        html_content
    )
    # H3 headers: font-size: 0.8em → add class="header-h3"
    html_content = re.sub(
        r'<span style="color: #ca5804; font-size: 0\.8em"',
        r'<span class="header-h3" style="color: #ca5804; font-size: 0.8em"',
        html_content
    )
    # H4 headers: font-size: 0.7em → add class="header-h4"
    html_content = re.sub(
        r'<span style="color: #ca5804; font-size: 0\.7em"',
        r'<span class="header-h4" style="color: #ca5804; font-size: 0.7em"',
        html_content
    )
    
    return html_content




def add_header_anchors(html_content: str) -> str:
    """Add anchor IDs to headers in the HTML content.
    
    Modifies colored span headers to include IDs for TOC linking.
    Also adds roman numerals to main headers and back-to-top links.
    
    Args:
        html_content: The rendered HTML content
        
    Returns:
        HTML content with header anchor IDs, roman numerals, and back-to-top links added
    """
    import re
    
    def int_to_roman(num: int) -> str:
        """Convert an integer to roman numerals."""
        values = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1]
        numerals = ['M', 'CM', 'D', 'CD', 'C', 'XC', 'L', 'XL', 'X', 'IX', 'V', 'IV', 'I']
        result = ''
        for i, val in enumerate(values):
            count = num // val
            if count:
                result += numerals[i] * count
                num -= val * count
        return result
    
    # Find all headers and add IDs
    # Pattern must capture full style attribute including optional "; font-size: 0.9em"
    # Allow for attributes on the <p> tag (e.g., data-force-break="true")
    header_pattern = r'<p(?:[^>]*)><span([^>]*)>([^<]+)</span></p>'
    
    def should_process_header(span_attrs: str) -> bool:
        """Check if this span is a header (has the header color or header CSS class)."""
        return ('style="color: #ca5804' in span_attrs or "style='color: #ca5804" in span_attrs 
                or 'style="color: #cd490a' in span_attrs or "style='color: #cd490a" in span_attrs
                or 'class="header-h' in span_attrs or "class='header-h" in span_attrs)
    
    def get_header_level(span_attrs: str) -> str:
        """Get the semantic header level from CSS class.
        
        [HEADER_NUMERALS] Only H1 headers get Roman numerals, not H2/H3/H4.
        
        Returns:
            'h1' for main headers, 'h2' for subheaders, 'h3' for sub-subheaders, 'h4' for smallest
        """
        if 'class="header-h2"' in span_attrs or "class='header-h2'" in span_attrs:
            return 'h2'
        elif 'class="header-h3"' in span_attrs or "class='header-h3'" in span_attrs:
            return 'h3'
        elif 'class="header-h4"' in span_attrs or "class='header-h4'" in span_attrs:
            return 'h4'
        elif 'class="header-h1"' in span_attrs or "class='header-h1'" in span_attrs:
            return 'h1'
        else:
            # Backward compatibility: check for font-size-based styling
            # This allows gradual migration to CSS classes
            if 'font-size: 0.9em' in span_attrs:
                return 'h2'
            elif 'font-size: 0.8em' in span_attrs:
                return 'h3'
            elif 'font-size: 0.7em' in span_attrs:
                return 'h4'
            # Default to H1 if no class or font-size indicator
            return 'h1'
    
    def should_add_roman_numeral(span_attrs: str) -> bool:
        """Check if this header should get a roman numeral.
        
        [HEADER_NUMERALS] Only H1 headers get Roman numerals.
        """
        return get_header_level(span_attrs) == 'h1'
    
    def replace_header(match):
        span_attrs = match.group(1)
        header_text = match.group(2)
        
        # Only process if this is actually a header (has the header color)
        if not should_process_header(span_attrs):
            return match.group(0)  # Return unchanged
        
        # Create a slug-friendly ID
        counter = replace_header.counter
        replace_header.counter += 1
        header_id = f"header-{counter}-{header_text.lower().replace(' ', '-').replace(':', '').replace('(', '').replace(')', '').replace(',', '')}"
        
        # [HEADER_NUMERALS] Add roman numerals to main headers (H1 only, not H2/H3/H4)
        # Check semantic header level via CSS class or font-size (backward compat)
        display_text = header_text
        if should_add_roman_numeral(span_attrs):
            # This is an H1 header - add roman numeral
            roman_counter = replace_header.roman_counter
            replace_header.roman_counter += 1
            roman_numeral = int_to_roman(roman_counter)
            # Place roman numeral outside the colored span so tests can match the raw header text
            # Visual result: "X. " before the colored header span
            prefix = f"{roman_numeral}. "
        else:
            prefix = ""
        
        # [HEADER_FORMAT] Add back-to-top link after every header
        back_to_top = ' <a href="#top" style="font-size: 0.8em; text-decoration: none;">[^]</a>'
        
        # Add appropriate class attribute for semantic header conversion
        header_level = get_header_level(span_attrs)
        class_attr = f' class="{header_level}-header"'
        
        return f'<p id="{header_id}"{class_attr}>{prefix}{back_to_top} <span{span_attrs}>{display_text}</span></p>'
    
    replace_header.counter = 0
    replace_header.roman_counter = 1
    
    # Add an anchor at the top of the document for back-to-top links
    if '<body>' in html_content:
        html_content = html_content.replace('<body>', '<body><a id="top"></a>')
    else:
        # If no <body> tag, add it at the beginning
        html_content = '<a id="top"></a>' + html_content
    
    return re.sub(header_pattern, replace_header, html_content)




